[log]
level = "warm"

[log.file]
enabled = true
level = "info"
path = "/tmp/oi"

[service]
host = "0.0.0.0"
port = 8080
prefix = "/"

[service.database]
uri = "postgres://postgres:po3tGre%y@127.0.0.1:5432/postgres"
