# console logging
[log]
# set directives for console logging, see also https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives
directives = "warn"

# file logging
[log.file]
# enable/disable file logging
enabled = true
# set log file path for file logging
path = "/tmp/olivier"
# set directives for file logging, see also https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives
directives = "info"

# http service
[service]
# listened address
host = "0.0.0.0"
# listened port
port = 8080
# api path, must end with '/'
prefix = "/"

# database
[database]
# database uri
uri = "postgres://postgres:postgres@127.0.0.1:5432/postgres"
